name: Build and Deploy

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
      - name: Build
        run: |
          bundle install
          mkdir -p ./build
          bundle exec ruby build.rb -s dictionary -f html > build/index.html
          bundle exec ruby build.rb -s dictionary -f json > build/characteristics.json
          bundle exec ruby build.rb -s changelog -f md > build/changelog.md
          bundle exec ruby build.rb -s changelog -f html > build/changelog.html
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Debug
        run: ls -la
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
