name: Run RSpec tests
on: [push]
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
      - name: Install gems (without development)
        run: |
          bundle config set --local without development
          bundle install --jobs 4
      - name: Run tests
        run: |
          bundle exec rspec